In [1]:
#Cleaning dataset Experiment ROster
#Que informacion tiene? Tiene solo dos columnas: client_id y variation, que te indica que cliente esta en el grupo control o en el grupo test.

In [3]:
#1. Importar dataset

import pandas as pd
df_exp = pd.read_csv("Datasets/df_final_experiment_clients.txt")

In [4]:
#2.a. Exploracion del dataset
df_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  50500 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.1+ MB

In [5]:
df_exp.shape

(70609, 2)

In [6]:
df_exp.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [7]:
#2.b Revisar los valores nulos
df_exp.isnull().sum()
#Importante: en la columna Variation tenemos un total de 20109 valores nulos. 
#Aqui podemos considerar varias hipotesis: error de datos, clientes no asignados o clientes no incluidos en el experimento.

client_id        0
Variation    20109
dtype: int64

In [8]:
#Vamos a comprobar los valores que presentan la variable Variation. 
df_exp["Variation"].value_counts(dropna=False)

Variation
Test       26968
Control    23532
NaN        20109
Name: count, dtype: int64

In [8]:
#Aqui podemos ver que los 20109 valores nulos, no son errores. Sino que, en el experimento no participaron todos los clientes activos de Vanguard, sino una muestra fue asignada al proyecto. 
#Con este resultado, considero que la decision seria eliminar los valores NaN del analisis, porque no aporta informacion al objetivo del analisis: analizar el A/B testing entre grupo test y grupo control.

In [9]:
#Vamos a eliminar los valores Nan de la columna Variation.
df_exp = df_exp.dropna(subset=["Variation"])

In [10]:
#Comprobacion de que se han borrado correctamente. 
df_exp["Variation"].value_counts(dropna=False)

Variation
Test       26968
Control    23532
Name: count, dtype: int64

In [11]:
#2.c Revisar los duplicados.
#En este caso, vamos a revisar que la columna de client_id no presenta duplicados. 
df_exp["client_id"].duplicated().sum()

#Vemos que no presenta duplicados, valor entre parentesis = 0

np.int64(0)

In [12]:
#2.d Corregir el nombre de las columnas. 
df_exp = df_exp.rename(columns={"Variation": "variation"})
df_exp

       client_id variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

In [13]:
#2.e Convertir dataset limpio a CSV y guardar en carpeta Datasets_limpios
df_exp.to_csv("Datasets_limpios/clean_experiment_clients.csv", index=False)